/**
 * CodexMigrationTool.jsx
 * 
 * ═══════════════════════════════════════════════════════════════════════════════
 * 🔗 TREE-CODEX INTEGRATION: Migration Tool for Existing People
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * PURPOSE:
 * Creates Codex entries for people who existed before the Tree-Codex integration.
 * This is a one-time migration tool that:
 * 1. Finds all people without a codexEntryId
 * 2. Creates skeleton Codex entries for each
 * 3. Links the person to their new Codex entry
 * 
 * USAGE:
 * This component is included in the Import/Export tab of Data Management.
 * Users can run the migration with a single click, with preview and confirmation.
 * 
 * ═══════════════════════════════════════════════════════════════════════════════
 */

import { useState } from 'react';
import { useGenealogy } from '../contexts/GenealogyContext';
import { createEntry as createCodexEntry } from '../services/codexService';
import { updatePerson as dbUpdatePerson } from '../services/database';

function CodexMigrationTool() {
  const { people, houses, refreshData } = useGenealogy();
  
  // Migration state
  const [migrationStatus, setMigrationStatus] = useState('idle'); // idle, previewing, migrating, complete, error
  const [migrationProgress, setMigrationProgress] = useState({ current: 0, total: 0 });
  const [migrationResults, setMigrationResults] = useState({ success: 0, failed: 0, skipped: 0 });
  const [errorMessage, setErrorMessage] = useState('');
  const [migrationLog, setMigrationLog] = useState([]);
  
  // Find people who need Codex entries
  const peopleNeedingMigration = people.filter(person => !person.codexEntryId);
  const peopleWithCodex = people.filter(person => person.codexEntryId);
  
  /**
   * Get house name by ID for display
   */
  const getHouseName = (houseId) => {
    const house = houses.find(h => h.id === houseId);
    return house ? house.houseName : 'No House';
  };
  
  /**
   * Build subtitle from person data (matches auto-creation logic)
   */
  const buildSubtitle = (person) => {
    let lifeDates = '';
    if (person.dateOfBirth) {
      lifeDates = `b. ${person.dateOfBirth}`;
      if (person.dateOfDeath) {
        lifeDates += ` - d. ${person.dateOfDeath}`;
      }
    } else if (person.dateOfDeath) {
      lifeDates = `d. ${person.dateOfDeath}`;
    }
    
    let subtitle = '';
    if (person.maidenName && lifeDates) {
      subtitle = `née ${person.maidenName} | ${lifeDates}`;
    } else if (person.maidenName) {
      subtitle = `née ${person.maidenName}`;
    } else if (lifeDates) {
      subtitle = lifeDates;
    }
    
    return subtitle || null;
  };
  
  /**
   * Add to migration log
   */
  const addLog = (message, type = 'info') => {
    const timestamp = new Date().toLocaleTimeString();
    setMigrationLog(prev => [...prev, { timestamp, message, type }]);
  };
  
  /**
   * Run the migration
   */
  const runMigration = async () => {
    if (peopleNeedingMigration.length === 0) {
      setMigrationStatus('complete');
      return;
    }
    
    setMigrationStatus('migrating');
    setMigrationProgress({ current: 0, total: peopleNeedingMigration.length });
    setMigrationResults({ success: 0, failed: 0, skipped: 0 });
    setMigrationLog([]);
    
    addLog(`Starting migration for ${peopleNeedingMigration.length} people...`, 'info');
    
    let successCount = 0;
    let failedCount = 0;
    
    for (let i = 0; i < peopleNeedingMigration.length; i++) {
      const person = peopleNeedingMigration[i];
      const fullName = `${person.firstName} ${person.lastName}`;
      
      setMigrationProgress({ current: i + 1, total: peopleNeedingMigration.length });
      
      try {
        // Create Codex entry
        const codexEntryId = await createCodexEntry({
          type: 'personage',
          title: fullName,
          subtitle: buildSubtitle(person),
          content: '', // Empty - user will fill in biography
          category: 'Personages',
          tags: [],
          era: null,
          personId: person.id,
          houseId: person.houseId || null,
          genealogyData: {
            dateOfBirth: person.dateOfBirth || null,
            dateOfDeath: person.dateOfDeath || null,
            gender: person.gender || null,
            legitimacyStatus: person.legitimacyStatus || null,
            maidenName: person.maidenName || null
          },
          isAutoGenerated: true,
          isMigrated: true // Flag to identify migrated entries
        });
        
        // Update person with codexEntryId
        await dbUpdatePerson(person.id, { codexEntryId: codexEntryId });
        
        successCount++;
        addLog(`✅ Created Codex entry for ${fullName} (ID: ${codexEntryId})`, 'success');
        
      } catch (err) {
        failedCount++;
        addLog(`❌ Failed to migrate ${fullName}: ${err.message}`, 'error');
        console.error(`Migration failed for ${fullName}:`, err);
      }
      
      // Small delay to prevent overwhelming the database
      await new Promise(resolve => setTimeout(resolve, 50));
    }
    
    setMigrationResults({ success: successCount, failed: failedCount, skipped: 0 });
    
    if (failedCount === 0) {
      addLog(`🎉 Migration complete! ${successCount} entries created.`, 'success');
      setMigrationStatus('complete');
    } else {
      addLog(`⚠️ Migration finished with ${failedCount} errors.`, 'warning');
      setMigrationStatus('complete');
    }
    
    // Refresh the genealogy context to update local state
    await refreshData();
  };
  
  /**
   * Reset the tool to initial state
   */
  const resetTool = () => {
    setMigrationStatus('idle');
    setMigrationProgress({ current: 0, total: 0 });
    setMigrationResults({ success: 0, failed: 0, skipped: 0 });
    setMigrationLog([]);
    setErrorMessage('');
  };
  
  return (
    <div className="codex-migration-tool">
      {/* Header */}
      <div className="migration-header">
        <h3 className="migration-title">
          <span className="title-icon">🔗</span>
          Codex Migration Tool
        </h3>
        <p className="migration-description">
          Create Codex biography entries for people added before the Tree-Codex integration.
        </p>
      </div>
      
      {/* Status Summary */}
      <div className="migration-summary">
        <div className="summary-item">
          <span className="summary-value">{peopleWithCodex.length}</span>
          <span className="summary-label">People with Codex entries</span>
        </div>
        <div className="summary-item highlight">
          <span className="summary-value">{peopleNeedingMigration.length}</span>
          <span className="summary-label">People needing migration</span>
        </div>
        <div className="summary-item">
          <span className="summary-value">{people.length}</span>
          <span className="summary-label">Total people</span>
        </div>
      </div>
      
      {/* Migration Actions */}
      {migrationStatus === 'idle' && (
        <div className="migration-actions">
          {peopleNeedingMigration.length === 0 ? (
            <div className="migration-complete-message">
              <span className="complete-icon">✅</span>
              <p>All people already have Codex entries! No migration needed.</p>
            </div>
          ) : (
            <>
              {/* Preview List */}
              <div className="preview-section">
                <h4>People to be migrated:</h4>
                <div className="preview-list">
                  {peopleNeedingMigration.slice(0, 10).map(person => (
                    <div key={person.id} className="preview-item">
                      <span className="preview-name">
                        {person.firstName} {person.lastName}
                      </span>
                      <span className="preview-house">
                        {getHouseName(person.houseId)}
                      </span>
                      {person.dateOfBirth && (
                        <span className="preview-dates">
                          b. {person.dateOfBirth}
                        </span>
                      )}
                    </div>
                  ))}
                  {peopleNeedingMigration.length > 10 && (
                    <div className="preview-more">
                      ...and {peopleNeedingMigration.length - 10} more
                    </div>
                  )}
                </div>
              </div>
              
              <button 
                onClick={runMigration}
                className="migration-button primary"
              >
                <span className="button-icon">🚀</span>
                Create {peopleNeedingMigration.length} Codex Entries
              </button>
              
              <p className="migration-note">
                This will create skeleton Codex entries with name, dates, and house info.
                You can add detailed biographies later in The Codex.
              </p>
            </>
          )}
        </div>
      )}
      
      {/* Migration Progress */}
      {migrationStatus === 'migrating' && (
        <div className="migration-progress">
          <div className="progress-header">
            <span className="progress-icon">⏳</span>
            <span className="progress-text">
              Migrating... {migrationProgress.current} / {migrationProgress.total}
            </span>
          </div>
          
          <div className="progress-bar-container">
            <div 
              className="progress-bar-fill"
              style={{ 
                width: `${(migrationProgress.current / migrationProgress.total) * 100}%` 
              }}
            />
          </div>
          
          <div className="progress-log">
            {migrationLog.slice(-5).map((log, index) => (
              <div key={index} className={`log-entry ${log.type}`}>
                <span className="log-time">{log.timestamp}</span>
                <span className="log-message">{log.message}</span>
              </div>
            ))}
          </div>
        </div>
      )}
      
      {/* Migration Complete */}
      {migrationStatus === 'complete' && (
        <div className="migration-complete">
          <div className="complete-header">
            <span className="complete-icon">🎉</span>
            <h4>Migration Complete!</h4>
          </div>
          
          <div className="complete-stats">
            <div className="stat success">
              <span className="stat-value">{migrationResults.success}</span>
              <span className="stat-label">Entries Created</span>
            </div>
            {migrationResults.failed > 0 && (
              <div className="stat failed">
                <span className="stat-value">{migrationResults.failed}</span>
                <span className="stat-label">Failed</span>
              </div>
            )}
          </div>
          
          {/* Full Log */}
          <details className="migration-log-details">
            <summary>View Full Log ({migrationLog.length} entries)</summary>
            <div className="full-log">
              {migrationLog.map((log, index) => (
                <div key={index} className={`log-entry ${log.type}`}>
                  <span className="log-time">{log.timestamp}</span>
                  <span className="log-message">{log.message}</span>
                </div>
              ))}
            </div>
          </details>
          
          <button 
            onClick={resetTool}
            className="migration-button secondary"
          >
            Done
          </button>
        </div>
      )}
      
      {/* Inline Styles (for portability) */}
      <style>{`
        .codex-migration-tool {
          background: var(--bg-tertiary, #f5f0e6);
          border: 2px solid var(--border-primary, #8b7355);
          border-radius: 12px;
          padding: 1.5rem;
          margin-top: 1rem;
        }
        
        .migration-header {
          margin-bottom: 1.5rem;
        }
        
        .migration-title {
          font-family: var(--font-heading, 'Cinzel', serif);
          font-size: 1.25rem;
          color: var(--text-primary, #2d1810);
          margin: 0 0 0.5rem 0;
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }
        
        .title-icon {
          font-size: 1.5rem;
        }
        
        .migration-description {
          font-family: var(--font-body, 'Crimson Text', serif);
          color: var(--text-secondary, #5c4a3a);
          margin: 0;
          font-size: 0.9rem;
        }
        
        .migration-summary {
          display: flex;
          gap: 1rem;
          margin-bottom: 1.5rem;
        }
        
        .summary-item {
          flex: 1;
          background: var(--bg-secondary, #fff);
          border: 1px solid var(--border-secondary, #c4b59d);
          border-radius: 8px;
          padding: 1rem;
          text-align: center;
        }
        
        .summary-item.highlight {
          background: var(--house-gold, #c9a227);
          border-color: var(--house-gold, #c9a227);
        }
        
        .summary-item.highlight .summary-value,
        .summary-item.highlight .summary-label {
          color: var(--bg-primary, #1a1408);
        }
        
        .summary-value {
          display: block;
          font-family: var(--font-display, 'Cinzel Decorative', serif);
          font-size: 2rem;
          font-weight: bold;
          color: var(--text-primary, #2d1810);
        }
        
        .summary-label {
          display: block;
          font-family: var(--font-body, 'Crimson Text', serif);
          font-size: 0.8rem;
          color: var(--text-secondary, #5c4a3a);
          margin-top: 0.25rem;
        }
        
        .migration-actions {
          text-align: center;
        }
        
        .migration-complete-message {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 0.75rem;
          padding: 1rem;
          background: rgba(34, 197, 94, 0.1);
          border: 1px solid rgba(34, 197, 94, 0.3);
          border-radius: 8px;
          color: #166534;
        }
        
        .complete-icon {
          font-size: 1.5rem;
        }
        
        .preview-section {
          text-align: left;
          margin-bottom: 1rem;
        }
        
        .preview-section h4 {
          font-family: var(--font-body, 'Crimson Text', serif);
          color: var(--text-secondary, #5c4a3a);
          margin: 0 0 0.5rem 0;
          font-size: 0.9rem;
        }
        
        .preview-list {
          max-height: 200px;
          overflow-y: auto;
          background: var(--bg-secondary, #fff);
          border: 1px solid var(--border-secondary, #c4b59d);
          border-radius: 8px;
        }
        
        .preview-item {
          display: flex;
          gap: 1rem;
          padding: 0.5rem 1rem;
          border-bottom: 1px solid var(--border-secondary, #c4b59d);
          font-family: var(--font-body, 'Crimson Text', serif);
          font-size: 0.9rem;
        }
        
        .preview-item:last-child {
          border-bottom: none;
        }
        
        .preview-name {
          flex: 1;
          font-weight: 600;
          color: var(--text-primary, #2d1810);
        }
        
        .preview-house {
          color: var(--text-tertiary, #8b7355);
          font-style: italic;
        }
        
        .preview-dates {
          color: var(--text-secondary, #5c4a3a);
        }
        
        .preview-more {
          padding: 0.5rem 1rem;
          color: var(--text-tertiary, #8b7355);
          font-style: italic;
          text-align: center;
        }
        
        .migration-button {
          display: inline-flex;
          align-items: center;
          gap: 0.5rem;
          padding: 0.75rem 1.5rem;
          font-family: var(--font-body, 'Crimson Text', serif);
          font-size: 1rem;
          font-weight: 600;
          border-radius: 8px;
          cursor: pointer;
          transition: all 0.2s ease;
          border: 2px solid transparent;
        }
        
        .migration-button.primary {
          background: var(--house-gold, #c9a227);
          color: var(--bg-primary, #1a1408);
          border-color: var(--house-gold, #c9a227);
        }
        
        .migration-button.primary:hover {
          background: var(--accent-secondary, #daa520);
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        }
        
        .migration-button.secondary {
          background: var(--bg-secondary, #fff);
          color: var(--text-primary, #2d1810);
          border-color: var(--border-primary, #8b7355);
        }
        
        .migration-button.secondary:hover {
          background: var(--bg-tertiary, #f5f0e6);
        }
        
        .button-icon {
          font-size: 1.25rem;
        }
        
        .migration-note {
          font-family: var(--font-body, 'Crimson Text', serif);
          font-size: 0.8rem;
          color: var(--text-tertiary, #8b7355);
          margin-top: 1rem;
          font-style: italic;
        }
        
        .migration-progress {
          text-align: center;
        }
        
        .progress-header {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 0.5rem;
          margin-bottom: 1rem;
        }
        
        .progress-icon {
          font-size: 1.5rem;
          animation: spin 1s linear infinite;
        }
        
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        
        .progress-text {
          font-family: var(--font-body, 'Crimson Text', serif);
          font-size: 1rem;
          color: var(--text-primary, #2d1810);
        }
        
        .progress-bar-container {
          width: 100%;
          height: 8px;
          background: var(--bg-secondary, #fff);
          border-radius: 4px;
          overflow: hidden;
          margin-bottom: 1rem;
        }
        
        .progress-bar-fill {
          height: 100%;
          background: var(--house-gold, #c9a227);
          transition: width 0.3s ease;
        }
        
        .progress-log {
          background: var(--bg-secondary, #fff);
          border: 1px solid var(--border-secondary, #c4b59d);
          border-radius: 8px;
          padding: 0.5rem;
          max-height: 150px;
          overflow-y: auto;
          text-align: left;
        }
        
        .log-entry {
          display: flex;
          gap: 0.5rem;
          padding: 0.25rem 0.5rem;
          font-family: monospace;
          font-size: 0.75rem;
        }
        
        .log-entry.success { color: #166534; }
        .log-entry.error { color: #dc2626; }
        .log-entry.warning { color: #ca8a04; }
        .log-entry.info { color: var(--text-secondary, #5c4a3a); }
        
        .log-time {
          color: var(--text-tertiary, #8b7355);
        }
        
        .log-message {
          flex: 1;
        }
        
        .migration-complete {
          text-align: center;
        }
        
        .complete-header {
          margin-bottom: 1rem;
        }
        
        .complete-header h4 {
          font-family: var(--font-heading, 'Cinzel', serif);
          color: var(--text-primary, #2d1810);
          margin: 0.5rem 0 0 0;
        }
        
        .complete-stats {
          display: flex;
          justify-content: center;
          gap: 2rem;
          margin-bottom: 1rem;
        }
        
        .stat {
          text-align: center;
        }
        
        .stat-value {
          display: block;
          font-family: var(--font-display, 'Cinzel Decorative', serif);
          font-size: 2rem;
          font-weight: bold;
        }
        
        .stat.success .stat-value { color: #166534; }
        .stat.failed .stat-value { color: #dc2626; }
        
        .stat-label {
          display: block;
          font-family: var(--font-body, 'Crimson Text', serif);
          font-size: 0.8rem;
          color: var(--text-secondary, #5c4a3a);
        }
        
        .migration-log-details {
          text-align: left;
          margin: 1rem 0;
        }
        
        .migration-log-details summary {
          cursor: pointer;
          font-family: var(--font-body, 'Crimson Text', serif);
          color: var(--text-secondary, #5c4a3a);
          font-size: 0.9rem;
        }
        
        .full-log {
          background: var(--bg-secondary, #fff);
          border: 1px solid var(--border-secondary, #c4b59d);
          border-radius: 8px;
          padding: 0.5rem;
          max-height: 200px;
          overflow-y: auto;
          margin-top: 0.5rem;
        }
      `}</style>
    </div>
  );
}

export default CodexMigrationTool;
